// <auto-generated />
using System;
using AccReporting.Server.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccReporting.Server.Migrations.AccountInfoDb
{
    [DbContext(typeof(AccountInfoDbContext))]
    [Migration("20220618172835_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccReporting.Shared.ContextModels.Acfile", b =>
                {
                    b.Property<int>("Idpr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPr");

                    b.Property<string>("ActCode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ActName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address3")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CrDays")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fax");

                    b.Property<string>("Gst")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("GST");

                    b.Property<double?>("OpBal")
                        .HasColumnType("double");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("Idpr")
                        .HasName("PK__Acfile__B87C5B5F3831C82B");

                    b.ToTable("Acfile", (string)null);
                });

            modelBuilder.Entity("AccReporting.Shared.ContextModels.Basic", b =>
                {
                    b.Property<int>("Idpr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPr");

                    b.Property<string>("ActCode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ActName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Sno")
                        .HasColumnType("int");

                    b.HasKey("Idpr")
                        .HasName("PK__Basic__B87C5B5FF0F4AE13");

                    b.ToTable("Basic", (string)null);
                });

            modelBuilder.Entity("AccReporting.Shared.ContextModels.Category", b =>
                {
                    b.Property<int>("Idpr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPr");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Date1")
                        .HasColumnType("datetime");

                    b.Property<string>("Item")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("JoiningType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Standard")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Temp1")
                        .HasColumnType("int");

                    b.Property<int?>("Temp2")
                        .HasColumnType("int");

                    b.Property<int?>("Temp3")
                        .HasColumnType("int");

                    b.Property<string>("Temp4")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Temp5")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Temp6")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Temp7")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Idpr")
                        .HasName("PK__Category__B87C5B5F9899F9B0");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("AccReporting.Shared.ContextModels.InvDet", b =>
                {
                    b.Property<int>("Idpr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPr");

                    b.Property<double?>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("CateCode")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<double?>("Dper")
                        .HasColumnType("double");

                    b.Property<string>("File")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("FILE");

                    b.Property<string>("Icode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ICode");

                    b.Property<string>("Iname")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IName");

                    b.Property<DateTime?>("InvDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("InvNo")
                        .HasColumnType("int");

                    b.Property<double?>("NetAmount")
                        .HasColumnType("double");

                    b.Property<string>("PName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pName");

                    b.Property<double?>("Packing")
                        .HasColumnType("double");

                    b.Property<string>("Pcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PCode");

                    b.Property<string>("Pressure")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<double?>("Qty")
                        .HasColumnType("double");

                    b.Property<double?>("Qty2")
                        .HasColumnType("double");

                    b.Property<double?>("Rate")
                        .HasColumnType("double");

                    b.Property<int?>("RegionCode")
                        .HasColumnType("int");

                    b.Property<string>("RegionName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Size")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Sp")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("SP");

                    b.Property<string>("Type")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Unit")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Idpr")
                        .HasName("PK__InvDet__B87C5B5F67F5802F");

                    b.ToTable("InvDet", (string)null);
                });

            modelBuilder.Entity("AccReporting.Shared.ContextModels.Inventory", b =>
                {
                    b.Property<int>("Idpr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPr");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ItemDescrip")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("Length")
                        .HasColumnType("double");

                    b.Property<string>("ManuName")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("MfcCode")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<double?>("OpBal")
                        .HasColumnType("double");

                    b.Property<string>("Pressure")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("RetPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("RetPrice2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Size")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Unit")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Idpr")
                        .HasName("PK__Inventor__B87C5B5F00A47D01");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("AccReporting.Shared.ContextModels.InvSumm", b =>
                {
                    b.Property<int>("Idpr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPr");

                    b.Property<double?>("AddLess")
                        .HasColumnType("double");

                    b.Property<double?>("Built")
                        .HasColumnType("double");

                    b.Property<double?>("Cartage")
                        .HasColumnType("double")
                        .HasColumnName("cartage");

                    b.Property<int?>("CrDays")
                        .HasColumnType("int");

                    b.Property<string>("Delivery")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("Dis")
                        .HasColumnType("double");

                    b.Property<double?>("DisPer")
                        .HasColumnType("double");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Hcode")
                        .HasColumnType("int")
                        .HasColumnName("HCode");

                    b.Property<DateTime?>("InvDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("InvNo")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Payment")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pcode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PCode");

                    b.Property<string>("Pname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PName");

                    b.Property<string>("RefNo")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("Ser")
                        .HasColumnType("double");

                    b.Property<double?>("TotBill")
                        .HasColumnType("double");

                    b.Property<string>("Type")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("Idpr")
                        .HasName("PK__InvSumm__B87C5B5F9C9191C6");

                    b.ToTable("InvSumm", (string)null);
                });

            modelBuilder.Entity("AccReporting.Shared.ContextModels.Trans", b =>
                {
                    b.Property<int>("Idpr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPr");

                    b.Property<string>("ActCode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ActName")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<DateTime?>("ChqDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ChqNo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Des")
                        .HasMaxLength(205)
                        .HasColumnType("varchar(205)");

                    b.Property<double?>("TransAmt")
                        .HasColumnType("double");

                    b.Property<string>("Vnoc")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int?>("Vnon")
                        .HasColumnType("int");

                    b.HasKey("Idpr")
                        .HasName("PK__Trans__B87C5B5F2A4B3E66");

                    b.ToTable("Trans");
                });
#pragma warning restore 612, 618
        }
    }
}
