// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AccReporting.Server;
using AccReporting.Server.DbContexts.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable enable

namespace AccReporting.Server.DbContexts
{
    public partial class AccountInfoDbContext : DbContext
    {
        public AccountInfoDbContext()
        {
        }

        public AccountInfoDbContext(DbContextOptions<AccountInfoDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Acfile> Acfiles { get; set; } = null!;
        public virtual DbSet<Basic> Basics { get; set; } = null!;
        public virtual DbSet<Category> Categories { get; set; } = null!;
        public virtual DbSet<InvDet> InvDets { get; set; } = null!;
        public virtual DbSet<InvSumm> InvSumms { get; set; } = null!;
        public virtual DbSet<Inventory> Inventories { get; set; } = null!;
        public virtual DbSet<Trans> Trans { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.AcfileConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BasicConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CategoryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.InvDetConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.InvSummConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.InventoryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TranConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
