// <auto-generated />
using AccReporting.Server.DbContexts;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace AccReporting.Server.OptimizedModels
{
    [DbContext(typeof(AccountInfoDbContext))]
    public partial class AccountInfoDbContextModel : RuntimeModel
    {
        static AccountInfoDbContextModel()
        {
            var model = new AccountInfoDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static AccountInfoDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
