// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace AccReporting.Server.OptimizedModels
{
    public partial class ApplicationDbContextModel
    {
        partial void Initialize()
        {
            var applicationUser = ApplicationUserEntityType.Create(this);
            var companyAccount = CompanyAccountEntityType.Create(this);
            var companyDetail = CompanyDetailEntityType.Create(this);
            var deviceFlowCodes = DeviceFlowCodesEntityType.Create(this);
            var key = KeyEntityType.Create(this);
            var persistedGrant = PersistedGrantEntityType.Create(this);
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaimstring = IdentityRoleClaimstringEntityType.Create(this);
            var identityUserClaimstring = IdentityUserClaimstringEntityType.Create(this);
            var identityUserLoginstring = IdentityUserLoginstringEntityType.Create(this);
            var identityUserRolestring = IdentityUserRolestringEntityType.Create(this);
            var identityUserTokenstring = IdentityUserTokenstringEntityType.Create(this);

            ApplicationUserEntityType.CreateForeignKey1(applicationUser, companyDetail);
            CompanyAccountEntityType.CreateForeignKey1(companyAccount, companyDetail);
            CompanyAccountEntityType.CreateForeignKey2(companyAccount, applicationUser);
            IdentityRoleClaimstringEntityType.CreateForeignKey1(identityRoleClaimstring, identityRole);
            IdentityUserClaimstringEntityType.CreateForeignKey1(identityUserClaimstring, applicationUser);
            IdentityUserLoginstringEntityType.CreateForeignKey1(identityUserLoginstring, applicationUser);
            IdentityUserRolestringEntityType.CreateForeignKey1(identityUserRolestring, identityRole);
            IdentityUserRolestringEntityType.CreateForeignKey2(identityUserRolestring, applicationUser);
            IdentityUserTokenstringEntityType.CreateForeignKey1(identityUserTokenstring, applicationUser);

            ApplicationUserEntityType.CreateAnnotations(applicationUser);
            CompanyAccountEntityType.CreateAnnotations(companyAccount);
            CompanyDetailEntityType.CreateAnnotations(companyDetail);
            DeviceFlowCodesEntityType.CreateAnnotations(deviceFlowCodes);
            KeyEntityType.CreateAnnotations(key);
            PersistedGrantEntityType.CreateAnnotations(persistedGrant);
            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimstringEntityType.CreateAnnotations(identityRoleClaimstring);
            IdentityUserClaimstringEntityType.CreateAnnotations(identityUserClaimstring);
            IdentityUserLoginstringEntityType.CreateAnnotations(identityUserLoginstring);
            IdentityUserRolestringEntityType.CreateAnnotations(identityUserRolestring);
            IdentityUserTokenstringEntityType.CreateAnnotations(identityUserTokenstring);

            AddAnnotation("ProductVersion", "6.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 64);
        }
    }
}
