// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AccReporting.Server;
using AccReporting.Server.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace AccReporting.Server.DbContexts.Configurations
{
    public partial class AcfileConfiguration : IEntityTypeConfiguration<Acfile>
    {
        public void Configure(EntityTypeBuilder<Acfile> entity)
        {
            entity.HasKey(e => e.Idpr)
                .HasName("PK__Acfile__B87C5B5F3831C82B");

            entity.ToTable("Acfile");

            entity.Property(e => e.Idpr).HasColumnName("IDPr");

            entity.Property(e => e.ActCode).HasMaxLength(30);

            entity.Property(e => e.ActName).HasMaxLength(50);

            entity.Property(e => e.Address1).HasMaxLength(50);

            entity.Property(e => e.Address2).HasMaxLength(50);

            entity.Property(e => e.Address3).HasMaxLength(50);

            entity.Property(e => e.Email)
                .HasMaxLength(40)
                .HasColumnName("email");

            entity.Property(e => e.Fax)
                .HasMaxLength(20)
                .HasColumnName("fax");

            entity.Property(e => e.Gst)
                .HasMaxLength(20)
                .HasColumnName("GST");

            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Acfile> entity);
    }
}
