// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AccReporting.Server;
using AccReporting.Server.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace AccReporting.Server.DbContexts.Configurations
{
    public partial class BasicConfiguration : IEntityTypeConfiguration<Basic>
    {
        public void Configure(EntityTypeBuilder<Basic> entity)
        {
            entity.HasKey(e => e.Idpr)
                .HasName("PK__Basic__B87C5B5FF0F4AE13");

            entity.ToTable("Basic");

            entity.Property(e => e.Idpr).HasColumnName("IDPr");

            entity.Property(e => e.ActCode).HasMaxLength(30);

            entity.Property(e => e.ActName).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Basic> entity);
    }
}
