// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AccReporting.Server;
using AccReporting.Server.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace AccReporting.Server.DbContexts.Configurations
{
    public partial class InvSummConfiguration : IEntityTypeConfiguration<InvSumm>
    {
        public void Configure(EntityTypeBuilder<InvSumm> entity)
        {
            entity.HasKey(e => e.Idpr)
                .HasName("PK__InvSumm__B87C5B5F9C9191C6");

            entity.ToTable("InvSumm");

            entity.Property(e => e.Idpr).HasColumnName("IDPr");

            entity.Property(e => e.Cartage).HasColumnName("cartage");

            entity.Property(e => e.Delivery).HasMaxLength(50);

            entity.Property(e => e.DueDate).HasColumnType("datetime");

            entity.Property(e => e.Hcode).HasColumnName("HCode");

            entity.Property(e => e.InvDate).HasColumnType("datetime");

            entity.Property(e => e.Note).HasMaxLength(150);

            entity.Property(e => e.OrderNo).HasMaxLength(50);

            entity.Property(e => e.Payment).HasMaxLength(50);

            entity.Property(e => e.Pcode)
                .HasMaxLength(30)
                .HasColumnName("PCode");

            entity.Property(e => e.Pname)
                .HasMaxLength(100)
                .HasColumnName("PName");

            entity.Property(e => e.RefNo).HasMaxLength(35);

            entity.Property(e => e.Remarks).HasMaxLength(50);

            entity.Property(e => e.Type).HasMaxLength(4);
            entity.HasIndex(x => x.InvNo).HasDatabaseName("InvNoIndex");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InvSumm> entity);
    }
}
