// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AccReporting.Server;
using AccReporting.Server.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace AccReporting.Server.DbContexts.Configurations
{
    public partial class TranConfiguration : IEntityTypeConfiguration<Trans>
    {
        public void Configure(EntityTypeBuilder<Trans> entity)
        {
            entity.HasKey(e => e.Idpr)
                .HasName("PK__Trans__B87C5B5F2A4B3E66");

            entity.Property(e => e.Idpr).HasColumnName("IDPr");

            entity.Property(e => e.ActCode).HasMaxLength(30);

            entity.Property(e => e.ActName).HasMaxLength(70);

            entity.Property(e => e.ChqDate).HasColumnType("datetime");

            entity.Property(e => e.ChqNo).HasMaxLength(15);

            entity.Property(e => e.Date).HasColumnType("datetime");

            entity.Property(e => e.Des).HasMaxLength(205);

            entity.Property(e => e.Vnoc).HasMaxLength(8);
            entity.HasIndex(e => e.ActCode).HasDatabaseName("ActCodeIndex");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Trans> entity);
    }
}
