// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AccReporting.Shared.Helpers;

using MySqlConnector;

using System;
using System.Collections.Generic;

namespace AccReporting.Shared.ContextModels
{
    public partial class Acfile
    {
        public Acfile(string[] x)
        {
            ActCode = MySqlHelper.EscapeString(x[0]);
            ActName = MySqlHelper.EscapeString(x[1]);
            OpBal = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[2]));
            Address1 = MySqlHelper.EscapeString(x[3]);
            Address2 = MySqlHelper.EscapeString(x[4]);
            Address3 = MySqlHelper.EscapeString(x[5]);
            Phone = MySqlHelper.EscapeString(x[6]);
            Fax = MySqlHelper.EscapeString(x[7]);
            Email = MySqlHelper.EscapeString(x[8]);
            Gst = MySqlHelper.EscapeString(x[9]);
            CrDays = ValOrDefault.ToInt(MySqlHelper.EscapeString(x[10]));


        }
        public Acfile()
        {
            
        }
        public string ToInsert()
        {
           //INSERT INTO `acfile`(`ActCode`,`ActName`,`Address1`,`Address2`,`Address3`,`CrDays`,`email`,`fax`,`GST`,`OpBal`,`phone`) VALUES
            return $"('{ActCode}','{ActName}','{Address1}','{Address2}','{Address3}',{CrDays??0},'{Email}','{Fax}','{Gst}',{OpBal??0},'{Phone}')";
        }
        public int Idpr { get; set; }
        public string ActCode { get; set; }
        public string ActName { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public double? OpBal { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Gst { get; set; }
        public int? CrDays { get; set; }
    }
}