// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AccReporting.Shared.Helpers;

using System;
using System.Collections.Generic;

namespace AccReporting.Shared.ContextModels
{
    public partial class Acfile
    {
        public Acfile(string[] x)
        {
            ActCode = x[0];
            ActName = x[1];
            OpBal = ValOrDefault.ToDouble(x[2]);
            Address1 = x[3];
            Address2 = x[4];
            Address3 = x[5];
            Phone = x[6];
            Fax = x[7];
            Email = x[8];
            Gst = x[9];
            CrDays = ValOrDefault.ToInt(x[10]);


        }
        public Acfile()
        {
            
        }
        public int Idpr { get; set; }
        public string ActCode { get; set; }
        public string ActName { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public double? OpBal { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Gst { get; set; }
        public int? CrDays { get; set; }
    }
}