// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccReporting.Shared.ContextModels
{
    public partial class Basic
    {
        public int Idpr { get; set; }
        public string ActCode { get; set; }
        public string ActName { get; set; }
        public int? Sno { get; set; }
    }
}