// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AccReporting.Shared.ContextModels
{
    public partial class Category
    {
        public int Idpr { get; set; }
        public string Code { get; set; }
        public string CategoryName { get; set; }
        public string Item { get; set; }
        public string Origin { get; set; }
        public string Standard { get; set; }
        public string Color { get; set; }
        public string JoiningType { get; set; }
        public string UserName { get; set; }
        public int? Temp1 { get; set; }
        public int? Temp2 { get; set; }
        public int? Temp3 { get; set; }
        public DateTime? Date1 { get; set; }
        public string Temp4 { get; set; }
        public string Temp5 { get; set; }
        public string Temp6 { get; set; }
        public string Temp7 { get; set; }
    }
}