// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AccReporting.Shared.Helpers;

using MySqlConnector;

using System;
using System.Collections.Generic;

namespace AccReporting.Shared.ContextModels
{
    public partial class InvDet
    {
        public InvDet(string[] x)
        {

            InvNo = ValOrDefault.ToInt(MySqlHelper.EscapeString(x[0]));
            InvDate = ValOrDefault.ToDateTime(MySqlHelper.EscapeString(x[1]));
            Pcode = MySqlHelper.EscapeString(x[2]);
            Icode = MySqlHelper.EscapeString(x[3]);
            Iname = MySqlHelper.EscapeString(x[4]);
            Qty = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[5]));
            Qty2 = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[6]));
            Unit = MySqlHelper.EscapeString(x[7]);
            Packing = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[8]));
            Rate = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[9]));
            Amount = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[10]));
            NetAmount = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[11]));
            Sp = MySqlHelper.EscapeString(x[12]);
            Type = MySqlHelper.EscapeString(x[13]);
            PName = MySqlHelper.EscapeString(x[14]);
            Size = MySqlHelper.EscapeString(x[15]);
            Pressure = MySqlHelper.EscapeString(x[16]);
            CateCode = MySqlHelper.EscapeString(x[17]);
            Dper = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[18]));
            RegionCode = ValOrDefault.ToInt(MySqlHelper.EscapeString(x[19]));
            RegionName = MySqlHelper.EscapeString(x[20]);
            File = MySqlHelper.EscapeString(x[21]);
        }
        public InvDet()
        {
            
        }
        public string ToInsert()
        {
            return $"({InvNo??0},'{(InvDate?? DateTime.MinValue):yyyy-MM-dd HH:mm:ss}','{Pcode}','{Icode}','{Iname}',{Qty??0},{Qty2??0},'{Unit}',{Packing??0},{Rate??0},{Amount??0},{NetAmount??0},'{Sp}','{Type}','{PName}','{Size}','{Pressure}','{CateCode}',{Dper??0},{RegionCode??0},'{RegionName}','{File}')";
        }
        public int Idpr { get; set; }
        public int? InvNo { get; set; }
        public DateTime? InvDate { get; set; }
        public string Pcode { get; set; }
        public string Icode { get; set; }
        public string Iname { get; set; }
        public double? Qty { get; set; }
        public double? Qty2 { get; set; }
        public string Unit { get; set; }
        public double? Packing { get; set; }
        public double? Rate { get; set; }
        public double? Amount { get; set; }
        public double? NetAmount { get; set; }
        public string Sp { get; set; }
        public string Type { get; set; }
        public string PName { get; set; }
        public string Size { get; set; }
        public string Pressure { get; set; }
        public string CateCode { get; set; }
        public double? Dper { get; set; }
        public int? RegionCode { get; set; }
        public string RegionName { get; set; }
        public string File { get; set; }
    }
}