// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AccReporting.Shared.Helpers;

using System;
using System.Collections.Generic;

namespace AccReporting.Shared.ContextModels
{
    public partial class Inventory
    {
        public Inventory(string[] x)
        {
            ItemCode = x[0];
            ItemDescrip = x[1];
            MfcCode = x[2];
            ManuName = x[3];
            Size = x[4];
            Pressure = x[5];
            Length = ValOrDefault.ToDouble(x[6]);
            Price = ValOrDefault.ToDecimal(x[7]);
            RetPrice = ValOrDefault.ToDecimal(x[8]);
            RetPrice2 = ValOrDefault.ToDecimal(x[9]);
            Unit = x[10];
            OpBal = ValOrDefault.ToDouble(x[11]);
        }
        public Inventory()
        {
            
        }
        public int Idpr { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescrip { get; set; }
        public string MfcCode { get; set; }
        public string ManuName { get; set; }
        public string Size { get; set; }
        public string Pressure { get; set; }
        public double? Length { get; set; }
        public decimal? Price { get; set; }
        public decimal? RetPrice { get; set; }
        public decimal? RetPrice2 { get; set; }
        public string Unit { get; set; }
        public double? OpBal { get; set; }
    }
}