// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AccReporting.Shared.Helpers;

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace AccReporting.Shared.ContextModels
{
    public partial class InvSumm
    {
        public InvSumm(string[] x)
        {
            try
            {

                OrderNo = x[0];
                InvNo = ValOrDefault.ToInt(x[1]);
                InvDate = ValOrDefault.ToDateTime(x[2]);
                Pcode = x[3];
                Pname = x[4];
                TotBill = ValOrDefault.ToDouble(x[5]);
                Built = ValOrDefault.ToDouble(x[6]);
                DisPer = ValOrDefault.ToDouble(x[7]);
                Dis = ValOrDefault.ToDouble(x[8]);
                Ser = ValOrDefault.ToDouble(x[9]);
                Remarks = x[10];
                Cartage = ValOrDefault.ToDouble(x[11]);
                AddLess = ValOrDefault.ToDouble(x[12]);
                CrDays = ValOrDefault.ToInt(x[13]);
                DueDate = ValOrDefault.ToDateTime(x[14]);
                RefNo = x[15];
                Payment = x[16];
                Note = x[17];
                Delivery = x[18];
                Hcode = ValOrDefault.ToInt(x[19]);
            }
            catch (IndexOutOfRangeException ex)
            {

#if DEBUG
                Debug.WriteLine(ex.Message + " " + ex.InnerException + " " + ex.StackTrace);
#endif
            }
        }
        public InvSumm()
        {
            
        }
        public int Idpr { get; set; }
        public string OrderNo { get; set; }
        public int? InvNo { get; set; }
        public DateTime? InvDate { get; set; }
        public string Pcode { get; set; }
        public string Pname { get; set; }
        public double? TotBill { get; set; }
        public double? Built { get; set; }
        public double? DisPer { get; set; }
        public double? Dis { get; set; }
        public double? Ser { get; set; }
        public string Remarks { get; set; }
        public string Type { get; set; }
        public double? Cartage { get; set; }
        public double? AddLess { get; set; }
        public int? CrDays { get; set; }
        public DateTime? DueDate { get; set; }
        public string RefNo { get; set; }
        public string Payment { get; set; }
        public string Note { get; set; }
        public string Delivery { get; set; }
        public int? Hcode { get; set; }
    }
}