// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AccReporting.Shared.Helpers;

using System;
using System.Collections.Generic;

namespace AccReporting.Shared.ContextModels
{
    public partial class Trans
    {
        public Trans(string[] x)
        {
            ActCode = x[0];
            ActName = x[1];
            Date = ValOrDefault.ToDateTime(x[2]);
            TransAmt = ValOrDefault.ToDouble(x[3]);
            Vnoc = x[4];
            Vnon = ValOrDefault.ToInt(x[5]);
            Des = x[6];
            ChqNo = x[7];
            ChqDate = ValOrDefault.ToDateTime(x[8]);
        }
        public Trans()
        {
            
        }
        public int Idpr { get; set; }
        public string ActCode { get; set; }
        public string ActName { get; set; }
        public DateTime? Date { get; set; }
        public double? TransAmt { get; set; }
        public string Vnoc { get; set; }
        public int? Vnon { get; set; }
        public string Des { get; set; }
        public string ChqNo { get; set; }
        public DateTime? ChqDate { get; set; }
    }
}