// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AccReporting.Shared.Helpers;

using MySqlConnector;

using System;
using System.Collections.Generic;

namespace AccReporting.Shared.ContextModels
{
    public partial class Trans
    {
        public Trans(string[] x)
        {
            ActCode = MySqlHelper.EscapeString(x[0]);
            ActName = MySqlHelper.EscapeString(x[1]);
            Date = ValOrDefault.ToDateTime(MySqlHelper.EscapeString(x[2]));
            TransAmt = ValOrDefault.ToDouble(MySqlHelper.EscapeString(x[3]));
            Vnoc = MySqlHelper.EscapeString(x[4]);
            Vnon = ValOrDefault.ToInt(MySqlHelper.EscapeString(x[5]));
            Des = MySqlHelper.EscapeString(x[6]);
            ChqNo = MySqlHelper.EscapeString(x[7]);
            ChqDate = ValOrDefault.ToDateTime(MySqlHelper.EscapeString(x[8]));
        }
        public Trans()
        {

        }
        public string ToInsert()
        {
            return $"('{ActCode}','{ActName}','{(ChqDate??DateTime.MinValue):yyyy-MM-dd HH:mm:ss}','{ChqNo}','{(Date ?? DateTime.MinValue):yyyy-MM-dd HH:mm:ss}','{Des}',{TransAmt??0},'{Vnoc}',{Vnon??0})";
        }
        public int Idpr { get; set; }
        public string ActCode { get; set; }
        public string ActName { get; set; }
        public DateTime? Date { get; set; }
        public double? TransAmt { get; set; }
        public string Vnoc { get; set; }
        public int? Vnon { get; set; }
        public string Des { get; set; }
        public string ChqNo { get; set; }
        public DateTime? ChqDate { get; set; }
    }
}